# Generated by Django 2.0.3 on 2018-04-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180331_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.BooksRead'),
        ),
    ]
