# Generated by Django 2.0.3 on 2018-03-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.TextField(default='el libro'),
            preserve_default=False,
        ),
    ]
