# Generated by Django 2.0.3 on 2018-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180331_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(default='43234gfsga', max_length=100),
            preserve_default=False,
        ),
    ]
