# Generated by Django 2.0.3 on 2018-04-19 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_friendlist_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendedbyfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookRecommendedByFriend_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrecommendedbyfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookRecommendedByFriend_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
